# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispatchConsole', '0002_auto_20160720_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentnature',
            name='code',
            field=models.CharField(default='none', max_length=4),
            preserve_default=False,
        ),
    ]
