# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispatchConsole', '0003_incidentnature_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='messages',
            field=models.ManyToManyField(to='DispatchConsole.Message'),
        ),
    ]
