# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispatchConsole', '0004_incident_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentmessage',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='incident',
            name='units',
            field=models.ManyToManyField(to='DispatchConsole.Unit'),
        ),
        migrations.DeleteModel(
            name='IncidentMessage',
        ),
    ]
